version: '3.8'

services:
  django_app:
    build:
      context: ./DjangoTaskManagementSystem
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  aspnet_app:
    build:
      context: ./AspNetCoreTaskManagementSystem
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: TaskManagement
      MYSQL_USER: TestUser
      MYSQL_PASSWORD: TestUser
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  mysql_data:
  grafana_data: