# Generated by Django 4.2.6 on 2023-10-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskplanned_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskplanned',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='taskplanned',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='taskplanned',
            old_name='Priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='taskplanned',
            old_name='Title',
            new_name='title',
        ),
    ]
