# Generated by Django 4.2.6 on 2023-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_deadline_taskplanned_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskplanned',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
    ]
